--------------------------------------------------------
--  File created - Wednesday-May-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTIVITE
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."ACTIVITE" 
   (	"ID_ACTIVITE" NUMBER, 
	"NOM_ACTIVITE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(255 BYTE), 
	"TEMPS" VARCHAR2(255 BYTE), 
	"DATEE" VARCHAR2(255 BYTE), 
	"RDV" VARCHAR2(255 BYTE), 
	"ID_ENFANT" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CAMERAS
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."CAMERAS" 
   (	"ID" NUMBER(*,0), 
	"MODELE" VARCHAR2(255 BYTE), 
	"ETAT" VARCHAR2(255 BYTE), 
	"EMPLACEMENT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAMBRE
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."CHAMBRE" 
   (	"NUM" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ELECTROMENAGER
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."ELECTROMENAGER" 
   (	"MATRICULE_MACHINE" NUMBER(*,0), 
	"TYPE_MACHINE" VARCHAR2(20 BYTE), 
	"ETAT_MACHINE" NUMBER, 
	"EMPLACEMENT_MACHINE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANTS
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."ENFANTS" 
   (	"ID_ENFANT" NUMBER, 
	"NOM_ENFANT" VARCHAR2(20 BYTE), 
	"PRENOM_ENFANT" VARCHAR2(20 BYTE), 
	"AGE_ENFANT" NUMBER, 
	"MATRICULE_PARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDINATEUR
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."ORDINATEUR" 
   (	"ID" NUMBER, 
	"MODELE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARENTS
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."PARENTS" 
   (	"MATRICULE_PARENTS" NUMBER(*,0), 
	"NOM_PARENTS" VARCHAR2(20 BYTE), 
	"PRENOM_PARENTS" VARCHAR2(20 BYTE), 
	"MAIL_PARENTS" VARCHAR2(20 BYTE), 
	"ADRESSE_PARENTS" VARCHAR2(20 BYTE), 
	"NUMERO_PARENTS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SITE
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."SITE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"NB_VISITE" VARCHAR2(255 BYTE), 
	"BLOCKAGE" VARCHAR2(255 BYTE), 
	"DATE_DV" VARCHAR2(20 BYTE), 
	"TEMPS_DV" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TELEVISION
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."TELEVISION" 
   (	"MATRICULE_TELE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"VEROUILLAGE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table THERMOMETRE
--------------------------------------------------------

  CREATE TABLE "OUMAYMA"."THERMOMETRE" 
   (	"MATRICULE_THERMO" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"TEMPERATURE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into OUMAYMA.ACTIVITE
SET DEFINE OFF;
Insert into OUMAYMA.ACTIVITE (ID_ACTIVITE,NOM_ACTIVITE,DESCRIPTION,DUREE,TEMPS,DATEE,RDV,ID_ENFANT) values (27,'testing','tets','01:00-02:00','01:00','06-01-2000','test',26);
REM INSERTING into OUMAYMA.CAMERAS
SET DEFINE OFF;
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (234,'trash','aa','kojina');
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (3445,'aa','aa',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (55,'aaaaa','aaaaaaaa',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (33,null,null,null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (4,'ee','aa',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (8,'qqq','fff',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (1,'f','f',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (7777,'4','a',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (4456,'tt','ee',null);
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (441,'aa','aa','aaa');
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (2444,'test','test','test');
Insert into OUMAYMA.CAMERAS (ID,MODELE,ETAT,EMPLACEMENT) values (2,'houssem','houssem','houssem');
REM INSERTING into OUMAYMA.CHAMBRE
SET DEFINE OFF;
Insert into OUMAYMA.CHAMBRE (NUM,DESCRIPTION) values ('33','aa');
REM INSERTING into OUMAYMA.ELECTROMENAGER
SET DEFINE OFF;
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (1,'refregirateur',1,'cuisine');
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (1239,'type2',2,'cuisine');
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (123,'frr',0,'exemple');
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (2021,'type',1,'salle');
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (4,'commande',1,'salon');
Insert into OUMAYMA.ELECTROMENAGER (MATRICULE_MACHINE,TYPE_MACHINE,ETAT_MACHINE,EMPLACEMENT_MACHINE) values (1598,'machine',0,'loft');
REM INSERTING into OUMAYMA.ENFANTS
SET DEFINE OFF;
Insert into OUMAYMA.ENFANTS (ID_ENFANT,NOM_ENFANT,PRENOM_ENFANT,AGE_ENFANT,MATRICULE_PARENT) values (25,'test','test',1,1);
Insert into OUMAYMA.ENFANTS (ID_ENFANT,NOM_ENFANT,PRENOM_ENFANT,AGE_ENFANT,MATRICULE_PARENT) values (26,'testing','testing',1,1);
Insert into OUMAYMA.ENFANTS (ID_ENFANT,NOM_ENFANT,PRENOM_ENFANT,AGE_ENFANT,MATRICULE_PARENT) values (27,'hh','jj',1,1);
REM INSERTING into OUMAYMA.ORDINATEUR
SET DEFINE OFF;
Insert into OUMAYMA.ORDINATEUR (ID,MODELE) values (555,'lol');
Insert into OUMAYMA.ORDINATEUR (ID,MODELE) values (55,'aaa');
REM INSERTING into OUMAYMA.PARENTS
SET DEFINE OFF;
Insert into OUMAYMA.PARENTS (MATRICULE_PARENTS,NOM_PARENTS,PRENOM_PARENTS,MAIL_PARENTS,ADRESSE_PARENTS,NUMERO_PARENTS) values (1,'testt','test','test','test',20021222);
Insert into OUMAYMA.PARENTS (MATRICULE_PARENTS,NOM_PARENTS,PRENOM_PARENTS,MAIL_PARENTS,ADRESSE_PARENTS,NUMERO_PARENTS) values (2,'sana','bh','lol@gmail.com','menzah',20002222);
REM INSERTING into OUMAYMA.SITE
SET DEFINE OFF;
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (1,'Ahmed','Hp','Ghazella','3','oui','Lundi',12);
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (3,'Islem','Hp','Ariana','8','oui','mardi',11);
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (6,'ikram','lenovo','touness','87','oui','2/1/2021',23);
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (5,'farid','lenovo','touness','32','oui','4/2/2021',23);
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (12,'farida','lenovo','touness','32','oui','4/2/2021',23);
Insert into OUMAYMA.SITE (ID,NOM,TYPE,ADRESSE,NB_VISITE,BLOCKAGE,DATE_DV,TEMPS_DV) values (4,'basma','msi','lol.com','45','oui','6/1/2021',12);
REM INSERTING into OUMAYMA.TELEVISION
SET DEFINE OFF;
REM INSERTING into OUMAYMA.THERMOMETRE
SET DEFINE OFF;
Insert into OUMAYMA.THERMOMETRE (MATRICULE_THERMO,ETAT,EMPLACEMENT,TEMPERATURE) values ('34','Chambre','En panne',987);
Insert into OUMAYMA.THERMOMETRE (MATRICULE_THERMO,ETAT,EMPLACEMENT,TEMPERATURE) values ('zz','Chambre','Bonne Etat',0);
--------------------------------------------------------
--  DDL for Index ACTIVITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."ACTIVITE_PK" ON "OUMAYMA"."ACTIVITE" ("ID_ACTIVITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAMERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."CAMERA_PK" ON "OUMAYMA"."CAMERAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAMBRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."CHAMBRE_PK" ON "OUMAYMA"."CHAMBRE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ELECTROMENAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."ELECTROMENAGER_PK" ON "OUMAYMA"."ELECTROMENAGER" ("MATRICULE_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENFANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."ENFANTS_PK" ON "OUMAYMA"."ENFANTS" ("ID_ENFANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDINATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."ORDINATEUR_PK" ON "OUMAYMA"."ORDINATEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."COMPTE_PK" ON "OUMAYMA"."PARENTS" ("MATRICULE_PARENTS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TELEVISION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."TELEVISION_PK" ON "OUMAYMA"."TELEVISION" ("MATRICULE_TELE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index THERMOMETRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OUMAYMA"."THERMOMETRE_PK" ON "OUMAYMA"."THERMOMETRE" ("MATRICULE_THERMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACTIVITE
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ACTIVITE" MODIFY ("ID_ACTIVITE" NOT NULL ENABLE);
  ALTER TABLE "OUMAYMA"."ACTIVITE" ADD CONSTRAINT "ACTIVITE_PK" PRIMARY KEY ("ID_ACTIVITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMERAS
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."CAMERAS" ADD CONSTRAINT "CAMERA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OUMAYMA"."CAMERAS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAMBRE
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."CHAMBRE" ADD CONSTRAINT "CHAMBRE_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OUMAYMA"."CHAMBRE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ELECTROMENAGER
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ELECTROMENAGER" MODIFY ("MATRICULE_MACHINE" NOT NULL ENABLE);
  ALTER TABLE "OUMAYMA"."ELECTROMENAGER" ADD CONSTRAINT "ELECTROMENAGER_PK" PRIMARY KEY ("MATRICULE_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENFANTS
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ENFANTS" MODIFY ("ID_ENFANT" NOT NULL ENABLE);
  ALTER TABLE "OUMAYMA"."ENFANTS" ADD CONSTRAINT "ENFANTS_PK" PRIMARY KEY ("ID_ENFANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDINATEUR
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ORDINATEUR" ADD CONSTRAINT "ORDINATEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OUMAYMA"."ORDINATEUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARENTS
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."PARENTS" MODIFY ("MATRICULE_PARENTS" NOT NULL ENABLE);
  ALTER TABLE "OUMAYMA"."PARENTS" ADD CONSTRAINT "COMPTE_PK" PRIMARY KEY ("MATRICULE_PARENTS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SITE
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."SITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TELEVISION
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."TELEVISION" ADD CONSTRAINT "TELEVISION_PK" PRIMARY KEY ("MATRICULE_TELE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OUMAYMA"."TELEVISION" MODIFY ("MATRICULE_TELE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table THERMOMETRE
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."THERMOMETRE" ADD CONSTRAINT "THERMOMETRE_PK" PRIMARY KEY ("MATRICULE_THERMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OUMAYMA"."THERMOMETRE" MODIFY ("MATRICULE_THERMO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITE
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ACTIVITE" ADD CONSTRAINT "ACTIVITE_FK1" FOREIGN KEY ("ID_ENFANT")
	  REFERENCES "OUMAYMA"."ENFANTS" ("ID_ENFANT") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENFANTS
--------------------------------------------------------

  ALTER TABLE "OUMAYMA"."ENFANTS" ADD CONSTRAINT "ENFANTS_FK1" FOREIGN KEY ("MATRICULE_PARENT")
	  REFERENCES "OUMAYMA"."PARENTS" ("MATRICULE_PARENTS") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACTIVITE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "OUMAYMA"."ACTIVITE_TRG" 
BEFORE INSERT ON ACTIVITE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ACTIVITE IS NULL THEN
      SELECT ACTIVITE_SEQ.NEXTVAL INTO :NEW.ID_ACTIVITE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "OUMAYMA"."ACTIVITE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ENFANTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "OUMAYMA"."ENFANTS_TRG" 
BEFORE INSERT ON ENFANTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ENFANT IS NULL THEN
      SELECT ENFANTS_SEQ1.NEXTVAL INTO :NEW.ID_ENFANT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "OUMAYMA"."ENFANTS_TRG" ENABLE;
